{{- define "env" -}}
- name: DOMAIN_NAME
  valueFrom:
    configMapKeyRef:
      name: global-config
      key: domain
- name: DJANGO_DATABASE_NAME
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: name
- name: DJANGO_DATABASE_USER
  valueFrom:
    secretKeyRef:
      name: database-credentials
      key: user
- name: DJANGO_DATABASE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: database-credentials
      key: password
- name: DJANGO_DATABASE_HOST
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: host
- name: DJANGO_DATABASE_PORT
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: port
- name: DJANGO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: secret_key
- name: DJANGO_SOCIAL_AUTH_GITLAB_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: social_auth_gitlab_key
- name: DJANGO_SOCIAL_AUTH_GITLAB_SECRET
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: social_auth_gitlab_secret
- name: DJANGO_ENV
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: env
- name: DJANGO_SENTRY_DSN
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: sentry.dsn
{{- end -}}
