{{- define "env" -}}
- name: DOMAIN_NAME
  valueFrom:
    configMapKeyRef:
      name: global-config
      key: global.domain
- name: POSTGRES_DB
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: database.name
- name: POSTGRES_USER
  valueFrom:
    secretKeyRef:
      name: database-credentials
      key: database.user
- name: POSTGRES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: database-credentials
      key: database.password
- name: DJANGO_DATABASE_HOST
  valueFrom:
    configMapKeyRef:
      name: database-config
      key: database.host
- name: DJANGO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: backend.secret_key
- name: DJANGO_SOCIAL_AUTH_GITLAB_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: backend.social_auth_gitlab_key
- name: DJANGO_SOCIAL_AUTH_GITLAB_SECRET
  valueFrom:
    secretKeyRef:
      name: backend-secrets
      key: backend.social_auth_gitlab_secret
- name: DJANGO_ENV
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: backend.env
{{- end -}}
