apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  secret_key: {{ .Values.secrets.secret_key }}
  social_auth_gitlab_key: {{ .Values.secrets.social_auth_gitlab_key }}
  social_auth_gitlab_secret: {{ .Values.secrets.social_auth_gitlab_secret }}
  sentry.dsn: {{ .Values.secrets.sentry.dsn }}
