apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  backend.secret_key: {{ .Values.secrets.secret_key }}
  backend.social_auth_gitlab_key: {{ .Values.secrets.social_auth_gitlab_key }}
  backend.social_auth_gitlab_secret: {{ .Values.secrets.social_auth_gitlab_secret }}
