# Generated by Django 2.2.8 on 2020-01-30 08:25

import jnt_django_toolbox.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_remove_project_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roles', jnt_django_toolbox.models.fields.BitField((('FRONTEND_DEVELOPER', 'CH__FRONTEND_DEVELOPER'), ('BACKEND_DEVELOPER', 'CH__BACKEND_DEVELOPER'), ('PROJECT_MANAGER', 'CH__PROJECT_MANAGER'), ('DESIGNER', 'CH__DESIGNER'), ('TESTER', 'CH__TESTER'), ('CUSTOMER', 'CH__CUSTOMER')), default=0)),
                ('project', models.ForeignKey(help_text='HT__PROJECT', on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='VN__PROJECT')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__PROJECT_MEMBER',
                'verbose_name_plural': 'VN__PROJECT_MEMBERS',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
