# Generated by Django 3.0.4 on 2020-03-05 12:33

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='roles',
            field=bitfield.models.BitField([('FRONTEND_DEVELOPER', 'CH__FRONTEND_DEVELOPER'), ('BACKEND_DEVELOPER', 'CH__BACKEND_DEVELOPER'), ('PROJECT_MANAGER', 'CH__PROJECT_MANAGER'), ('DESIGNER', 'CH__DESIGNER'), ('TESTER', 'CH__TESTER'), ('CUSTOMER', 'CH__CUSTOMER')], default=0),
        ),
    ]
