# Generated by Django 3.0.5 on 2020-07-28 09:18

from django.db import migrations, models

import apps.projects.models.project


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200305_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(
                default=apps.projects.models.project.get_new_id,
                editable=False,
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
