# Generated by Django 3.0.5 on 2020-07-28 09:18

from django.db import migrations
from django.utils.baseconv import BASE64_ALPHABET
from django.utils.crypto import get_random_string


def generate_ids(count):
    new_ids = []

    for _iterate_number in range(count):  # noqa: WPS122
        uid = get_random_string(8, BASE64_ALPHABET)

        while uid in new_ids:
            uid = get_random_string(8, BASE64_ALPHABET)

        new_ids.append(uid)

    return new_ids


def update_ids(apps, schema_editor):
    """Update ids."""
    Project = apps.get_model("projects", "Project")  # noqa: N806

    apply_ids(
        Project.objects.values_list("id", flat=True),
        generate_ids(Project.objects.count()),
        apps,
        Project,
    )


def apply_ids(project_ids, ids, apps, Project):  # noqa: N803
    ProjectMember = apps.get_model("projects", "ProjectMember")  # noqa: N806

    for project_id, new_id in zip(project_ids, ids):
        Project.objects.filter(id=project_id).update(id=new_id)
        ProjectMember.objects.filter(project_id=project_id).update(
            project_id=new_id,
        )


class Migration(migrations.Migration):
    """Migration."""

    dependencies = [
        ('projects', '0012_auto_20200728_1218'),
    ]

    operations = [
        migrations.RunPython(update_ids),
    ]
