# Generated by Django 3.0.8 on 2020-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='db_name',
            field=models.CharField(blank=True, help_text='HT__DB_NAME', max_length=50, verbose_name='VN__DB_NAME'),
        ),
    ]
