# Generated by Django 3.1.1 on 2021-01-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_db_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='public',
            new_name='is_public',
        ),
    ]
