# Generated by Django 3.1.1 on 2021-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20210112_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False, help_text='HT__IS_PUBLIC', verbose_name='VN__IS_PUBLIC'),
        ),
    ]
