# Generated by Django 3.1.5 on 2021-02-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_integrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figmaintegration',
            name='project',
            field=models.OneToOneField(help_text='HT__PROJECT', on_delete=django.db.models.deletion.CASCADE, related_name='figma_integration', to='projects.project', verbose_name='VN__PROJECT'),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='project',
            field=models.OneToOneField(help_text='HT__PROJECT', on_delete=django.db.models.deletion.CASCADE, related_name='github_integration', to='projects.project', verbose_name='VN__PROJECT'),
        ),
        migrations.AlterField(
            model_name='gitlabintegration',
            name='project',
            field=models.OneToOneField(help_text='HT__PROJECT', on_delete=django.db.models.deletion.CASCADE, related_name='gitlab_integration', to='projects.project', verbose_name='VN__PROJECT'),
        ),
    ]
