# Generated by Django 3.1.5 on 2021-02-12 12:03

import apps.projects.models.project_asset
from django.db import migrations, models
import django.db.models.deletion
import jnt_django_toolbox.models.fields.enum


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20210208_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', jnt_django_toolbox.models.fields.enum.EnumField(choices=[('FIGMA', 'CH__FIGMA')], default='FIGMA', enum=apps.projects.models.project_asset.ProjectAssetSource, help_text='HT__PROJECT_ASSET_SOURCE', verbose_name='VN__PROJECT_ASSET_SOURCE')),
                ('file', models.FileField(blank=True, help_text='HT__FILE', max_length=256, upload_to=apps.projects.models.project_asset.assets_upload_to, verbose_name='VN__FILE')),
                ('project', models.ForeignKey(help_text='HT__PROJECT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='VN__PROJECT')),
            ],
            options={
                'verbose_name': 'VN__PROJECT_ASSET',
                'verbose_name_plural': 'VN__PROJECTS_ASSETS',
                'ordering': ('-created_at',),
            },
        ),
    ]
