# Generated by Django 3.1.7 on 2021-05-06 13:56

import apps.media.models.fields.image
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210506_1647'),
        ('projects', '0020_auto_20210506_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emblem',
            field=apps.media.models.fields.image.ImageField(blank=True, help_text='HT__EMBLEM', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.image', verbose_name='VN__EMBLEM'),
        ),
    ]
