# Generated by Django 3.1.10 on 2021-05-07 10:41

from django.db import migrations
import jnt_django_toolbox.models.fields.bit.field


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_emblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='permissions',
            field=jnt_django_toolbox.models.fields.bit.field.BitField([('EDIT_FEATURES', 'VN__EDIT_FEATURES'), ('EDIT_FEATURE_WORKFLOW', 'VN__EDIT_FEATURE_WORKFLOW'), ('EDIT_FEATURE_STORY', 'VN__EDIT_FEATURE_STORY'), ('EDIT_FEATURE_FRAMES', 'VN__EDIT_FEATURE_FRAMES'), ('EDIT_FEATURE_RESOURCES', 'VN__EDIT_FEATURE_RESOURCES'), ('EDIT_FEATURE_API', 'VN__EDIT_FEATURE_API'), ('EDIT_FEATURE_ISSUES', 'VN__EDIT_FEATURE_ISSUES'), ('EDIT_TERMS', 'VN__EDIT_TERMS'), ('EDIT_MODEL', 'VN__EDIT_MODEL'), ('EDIT_MODULES', 'VN__EDIT_MODULES'), ('EDIT_SPRINTS', 'VN__EDIT_SPRINTS'), ('VIEW_CONTRACT', 'VN__VIEW_CONTRACT')], default=0, help_text='HT__PROJECT_MEMBER_PERMISSIONS', verbose_name='VN__PROJECT_MEMBER_PERMISSIONS'),
        ),
    ]
