# Generated by Django 3.1.10 on 2021-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20210507_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'CH__VIEWER'), ('EDITOR', 'CH__EDITOR')], default='VIEWER', help_text='HT__ROLE', max_length=28, verbose_name='VN__ROLE'),
        ),
    ]
