# Generated by Django 3.1.10 on 2021-05-07 13:13

from django.db import migrations, models
import jnt_django_toolbox.models.fields.bit.field


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public_permissions',
            field=jnt_django_toolbox.models.fields.bit.field.BitField([('EDIT_FEATURES', 'CH__EDIT_FEATURES'), ('EDIT_FEATURE_WORKFLOW', 'CH__EDIT_FEATURE_WORKFLOW'), ('EDIT_FEATURE_STORY', 'CH__EDIT_FEATURE_STORY'), ('EDIT_FEATURE_FRAMES', 'CH__EDIT_FEATURE_FRAMES'), ('EDIT_FEATURE_RESOURCES', 'CH__EDIT_FEATURE_RESOURCES'), ('EDIT_FEATURE_API', 'CH__EDIT_FEATURE_API'), ('EDIT_FEATURE_ISSUES', 'CH__EDIT_FEATURE_ISSUES'), ('EDIT_TERMS', 'CH__EDIT_TERMS'), ('EDIT_MODEL', 'CH__EDIT_MODEL'), ('EDIT_MODULES', 'CH__EDIT_MODULES'), ('EDIT_SPRINTS', 'CH__EDIT_SPRINTS'), ('VIEW_CONTRACT', 'CH__VIEW_CONTRACT')], default=0, help_text='HT__PROJECT_PERMISSIONS', verbose_name='VN__PROJECT_PERMISSIONS'),
        ),
        migrations.AddField(
            model_name='project',
            name='public_role',
            field=models.CharField(choices=[('VIEWER', 'CH__VIEWER'), ('EDITOR', 'CH__EDITOR')], default='VIEWER', help_text='HT__ROLE', max_length=28, verbose_name='VN__ROLE'),
        ),
    ]
