# Generated by Django 3.1.10 on 2021-05-19 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20210507_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectasset',
            old_name='file',
            new_name='old_file',
        ),
    ]
