# Generated by Django 3.1.10 on 2021-05-19 13:12

import apps.media.models.fields.file
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_file'),
        ('projects', '0028_auto_20210519_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectasset',
            name='file',
            field=apps.media.models.fields.file.FileField(blank=True, help_text='HT__FILE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.file', verbose_name='VN__FILE'),
        ),
    ]
