image: docker:latest

variables:
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE/cache
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE/tmp:${CI_PIPELINE_ID}_${CI_COMMIT_SHA}
  DOCKER_TEST_IMAGE: $CI_REGISTRY_IMAGE/tmp:${CI_PIPELINE_ID}_${CI_COMMIT_SHA}_test

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  services:
    - docker:dind
  script:
    - ./scripts/ci_build_images.sh
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_CACHE_IMAGE || true
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_TEST_IMAGE -t $DOCKER_CACHE_IMAGE --target test -f deploy/Dockerfile .
    - cat deploy/.dockerignore.production >> .dockerignore
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_IMAGE --target production -f deploy/Dockerfile .
    - docker push $DOCKER_TEST_IMAGE
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_CACHE_IMAGE

quality:
  stage: test
  image: $DOCKER_TEST_IMAGE
  script:
    - cd /app
    - make lint

test:
  image: $DOCKER_TEST_IMAGE
  stage: test
  variables:
    DJANGO_ENV: test
  services:
    - postgres:12.1
  script:
    - cd /app
    - pytest -n auto --cov-report=html:coverage_html
    - mkdir $CI_PROJECT_DIR/coverage
    - coverage report -m > $CI_PROJECT_DIR/coverage/report.log
    - cat $CI_PROJECT_DIR/coverage/report.log | tail -n 1
    - mv coverage_html $CI_PROJECT_DIR/coverage/html
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - coverage

.base_publish:
  stage: publish
  services:
    - docker:dind
  dependencies: []
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_IMAGE
  script:
    - docker tag $DOCKER_IMAGE $TARGET_IMAGE
    - docker push $TARGET_IMAGE

publish_unstable:
  extends: .base_publish
  only:
    - master
  variables:
    TARGET_IMAGE: $CI_REGISTRY_IMAGE/unstable:${CI_PIPELINE_ID}

.base_deploy:
  image: curlimages/curl:7.72.0
  stage: deploy
  dependencies: []
  script:
    - curl -k -X POST -d "component=${DEPLOYER_COMPONENT}&key=${DEPLOYER_KEY}&tag=${CI_PIPELINE_ID}" ${DEPLOYER_HOST}

deploy_development:
  extends: .base_deploy
  only:
    - master
  environment:
    name: development
    url: $SITE_ADDRESS
