[tool.poetry]
name = "spec_projector"
version = "0.1.0"
description = ""
authors = ["Junte Ltd"]

[tool.poetry.dependencies]
python = "^3.6"
python-decouple = "^3.1"
psycopg2-binary = "*"
django = "2.*"
django-admin-autocomplete-filter = "*"
django-health-check = "*"
django-cors-headers = "*"
django_extensions = "*"
django-split-settings = "*"
django-model-utils = "*"
django-filter = "*"
djangorestframework = "*"
drf-yasg = "*"
jnt-django-bitfield = "*"
jnt-django-admin-tools = "*"
social-auth-app-django = "^3.1"
social-auth-core = "^3.2"
graphene-django = "2.6.0"
uWSGI = "*"

[tool.poetry.dev-dependencies]
flake8 = "*"
factory-boy = "*"
mypy = "*"
polint = "^0.4.0"
dennis = "^0.9.0"
safety = "^1.8"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-xdist = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
