# Generated by Django 3.1.7 on 2021-05-06 10:44

import apps.media.models.image
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('storage_image', models.ImageField(help_text='HT__STORAGE_IMAGE', max_length=1000, upload_to=apps.media.models.image.get_upload_path, verbose_name='VN__STORAGE_IMAGE')),
                ('owner', models.ForeignKey(help_text='HT__OWNER', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='VN__OWNER')),
            ],
            options={
                'verbose_name': 'VN__IMAGE',
                'verbose_name_plural': 'VN__IMAGES',
            },
        ),
    ]
