# Generated by Django 3.1.7 on 2021-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='HT__CREATED_AT', verbose_name='VN__CREATED_AT'),
        ),
        migrations.AlterField(
            model_name='image',
            name='original_filename',
            field=models.CharField(blank=True, help_text='HT__ORIGINAL_FILENAME', max_length=512, verbose_name='VN__ORIGINAL_FILENAME'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='HT__UPDATED_AT', verbose_name='VN__UPDATED_AT'),
        ),
    ]
