# Generated by Django 3.1.10 on 2021-05-19 13:10

import apps.media.models.file
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0002_auto_20210506_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='HT__CREATED_AT', verbose_name='VN__CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='HT__UPDATED_AT', verbose_name='VN__UPDATED_AT')),
                ('storage_file', models.ImageField(help_text='HT__STORAGE_FILE', max_length=1000, upload_to=apps.media.models.file.get_upload_path, verbose_name='VN__STORAGE_FILE')),
                ('original_filename', models.CharField(blank=True, help_text='HT__ORIGINAL_FILENAME', max_length=512, verbose_name='VN__ORIGINAL_FILENAME')),
                ('owner', models.ForeignKey(help_text='HT__OWNER', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='VN__OWNER')),
            ],
            options={
                'verbose_name': 'VN__FILE',
                'verbose_name_plural': 'VN__FILES',
            },
        ),
    ]
