# Generated by Django 3.1.10 on 2021-05-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='owner',
            new_name='created_by',
        ),
    ]
