# Generated by Django 3.1.10 on 2021-05-25 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0004_auto_20210524_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(help_text='HT__CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='VN__CREATED_BY'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_by',
            field=models.ForeignKey(help_text='HT__CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='VN__CREATED_BY'),
        ),
    ]
