# Generated by Django 3.1.7 on 2021-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('created', 'CH__CREATED'), ('sent', 'CH__SENT'), ('error', 'CH__ERROR')], db_index=True, default='created', help_text='HT__EMAIL_MESSAGE_STATUS', max_length=50, verbose_name='VN__EMAIL_MESSAGE_STATUS')),
                ('subject', models.CharField(help_text='HT__EMAIL_MESSAGE_SUBJECT', max_length=255, verbose_name='VN__EMAIL_MESSAGE_SUBJECT')),
                ('to', models.EmailField(help_text='HT__EMAIL_MESSAGE_TO', max_length=254, verbose_name='VN__EMAIL_MESSAGE_TO')),
                ('html', models.TextField(default=None)),
                ('sender', models.EmailField(blank=True, help_text='HT__EMAIL_MESSAGE_SENDER', max_length=254, verbose_name='VN__EMAIL_MESSAGE_SENDER')),
                ('sent_at', models.DateTimeField(blank=True, help_text='HT__EMAIL_MESSAGE_SENT_AT', null=True, verbose_name='VN__EMAIL_MESSAGE_SENT_AT')),
                ('status_info', models.TextField(blank=True, help_text='HT__EMAIL_MESSAGE_STATUS_INFO', verbose_name='VN__EMAIL_MESSAGE_STATUS_INFO')),
            ],
            options={
                'verbose_name': 'VN__EMAIL_MESSAGE',
                'verbose_name_plural': 'VN__EMAIL_MESSAGES',
            },
        ),
    ]
