from .project_member import ProjectMemberInline
from .figma_integration import FigmaIntegrationInline
from .github_integration import GitHubIntegrationInline
from .gitlab_integration import GitLabIntegrationInline
