# Generated by Django 3.1.7 on 2021-04-01 08:57

import apps.core.models.fields.money
from django.db import migrations, models
import jnt_django_toolbox.models.fields.bit.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='HT__ORDER', verbose_name='VN__ORDER')),
                ('code', models.CharField(help_text='HT__CODE', max_length=64, verbose_name='VN__CODE')),
                ('title', models.CharField(help_text='HT__TITLE', max_length=128, verbose_name='VN__TITLE')),
                ('teaser', models.TextField(help_text='HT__TEASER', verbose_name='VN__TEASER')),
                ('icon', models.CharField(blank=True, help_text='HT__ICON', max_length=512, verbose_name='VN__ICON')),
                ('price', apps.core.models.fields.money.MoneyField(decimal_places=2, default=0, help_text='HT__PRICE', max_digits=14, verbose_name='VN__PRICE')),
                ('is_active', models.BooleanField(default=False, help_text='HT__IS_ACTIVE', verbose_name='VN__IS_ACTIVE')),
                ('features', jnt_django_toolbox.models.fields.bit.field.BitField([('PROJECT_MEMBERS_ROLES', 'CH__PROJECT_MEMBERS_ROLES'), ('PRINT_CONTRACT', 'CH__PRINT_CONTRACT'), ('EXPORT_IMPORT', 'CH__EXPORT_IMPORT'), ('COMMUNITY_CHAT', 'CH__COMMUNITY_CHAT'), ('SLACK_SUPPORT', 'CH__SLACK_SUPPORT'), ('EXCLUSIVE_SLACK_SUPPORT', 'CH__EXCLUSIVE_SLACK_SUPPORT')], default=0, help_text='HT__FEATURES', verbose_name='VN__FEATURES')),
                ('max_projects', models.PositiveIntegerField(default=0, help_text='HT__MAX_PROJECTS', verbose_name='VN__MAX_PROJECTS')),
                ('max_project_members', models.PositiveIntegerField(default=0, help_text='HT__MAX_PROJECT_MEMBERS', verbose_name='VN__MAX_PROJECT_MEMBERS')),
            ],
            options={
                'verbose_name': 'VN__TARIFF',
                'verbose_name_plural': 'VN__TARIFFS',
                'ordering': ('order',),
            },
        ),
    ]
