# Generated by Django 3.1.7 on 2021-04-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'VN__TARIFF', 'verbose_name_plural': 'VN__TARIFFS'},
        ),
    ]
