# Generated by Django 3.1.7 on 2021-04-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210405_0920'),
        ('billing', '0002_auto_20210405_1020'),
    ]

    operations = [
    ]
