# Generated by Django 3.1.7 on 2021-04-06 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_merge_20210405_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, help_text='HT__CREATED', verbose_name='VN__CREATED')),
                ('hash', models.CharField(db_index=True, help_text='HT__CREATED', max_length=128, verbose_name='VN__CREATED')),
                ('status', models.CharField(choices=[('CONFIRMING', 'CH__CONFIRMING'), ('ACTIVE', 'CH__ACTIVE'), ('CANCELED', 'CH__CANCELED'), ('OPTION', 'CH__OPTION'), ('EXPIRED', 'CH__EXPIRED')], help_text='HT__STATUS', max_length=16, verbose_name='VN__STATUS')),
                ('tariff', models.ForeignKey(help_text='HT__TARIFF', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tariff', verbose_name='VN__TARIFF')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__SUBSCRIPTION',
                'verbose_name_plural': 'VN__SUBSCRIPTION',
                'unique_together': {('user', 'hash')},
            },
        ),
    ]
