# Generated by Django 3.1.7 on 2021-04-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='HT__ACTIVE_UNTIL', null=True, verbose_name='VN__ACTIVE_UNTIL'),
        ),
    ]
