# Generated by Django 3.1.7 on 2021-04-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_subscription_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hash',
            field=models.CharField(db_index=True, help_text='HT__SUBSCRIPTION_HASH', max_length=128, verbose_name='VN__HASH'),
        ),
    ]
