# Generated by Django 3.1.7 on 2021-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20210406_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('CONFIRMING', 'CH__CONFIRMING'), ('ACTIVE', 'CH__ACTIVE'), ('CANCELED', 'CH__CANCELED'), ('OPTION', 'CH__OPTION'), ('EXPIRED', 'CH__EXPIRED')], help_text='HT__STATUS', max_length=10, verbose_name='VN__STATUS'),
        ),
    ]
