# Generated by Django 3.1.7 on 2021-04-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20210406_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='created',
            new_name='created_at',
        ),
    ]
