# Generated by Django 3.1.7 on 2021-04-07 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0010_auto_20210407_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'CH__ACTIVE'), ('PAST_DUE', 'CH__PAST_DUE'), ('CANCELED', 'CH__CANCELED'), ('REJECTED', 'CH__REJECTED'), ('EXPIRED', 'CH__EXPIRED')], help_text='HT__STATUS', max_length=8, verbose_name='VN__STATUS'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='hash',
        ),
        migrations.CreateModel(
            name='ChangeSubscriptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='HT__CREATED', verbose_name='VN__CREATED')),
                ('hash', models.CharField(db_index=True, help_text='HT__SUBSCRIPTION_HASH', max_length=128, verbose_name='VN__HASH')),
                ('is_active', models.BooleanField(default=True, help_text='HT__IS_ACTIVE', verbose_name='VN__IS_ACTIVE')),
                ('from_subscription', models.ForeignKey(help_text='HT__FROM_SUBSCRIPTION', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription', verbose_name='VN__FROM_SUBSCRIPTION')),
                ('tariff', models.ForeignKey(help_text='HT__TARIFF', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tariff', verbose_name='VN__TARIFF')),
                ('to_subscription', models.ForeignKey(help_text='HT__TO_SUBSCRIPTION', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription', verbose_name='VN__TO_SUBSCRIPTION')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, related_name='change_subscriptions_requests', to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__CHANGE_SUBSCRIPTION_REQUEST',
                'verbose_name_plural': 'VN__CHANGE_SUBSCRIPTION_REQUEST',
                'unique_together': {('user', 'hash')},
            },
        ),
    ]
