# Generated by Django 3.1.7 on 2021-04-07 10:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20210407_1206'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changesubscriptionrequest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='changesubscriptionrequest',
            constraint=models.UniqueConstraint(fields=('user', 'hash'), name='billing_changesubscriptionrequest_unique'),
        ),
        migrations.AddConstraint(
            model_name='changesubscriptionrequest',
            constraint=models.CheckConstraint(check=models.Q(from_subscription__ne=django.db.models.expressions.F('to_subscription')), name='billing_changesubscriptionrequest_subscriptions_not_equal'),
        ),
    ]
