# Generated by Django 3.1.7 on 2021-04-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20210407_1332'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='changesubscriptionrequest',
            name='billing_changesubscriptionrequest_subscriptions_not_equal',
        ),
    ]
