# Generated by Django 3.1.7 on 2021-04-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20210407_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changesubscriptionrequest',
            name='from_subscription',
            field=models.ForeignKey(blank=True, help_text='HT__FROM_SUBSCRIPTION', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription', verbose_name='VN__FROM_SUBSCRIPTION'),
        ),
        migrations.AlterField(
            model_name='changesubscriptionrequest',
            name='to_subscription',
            field=models.ForeignKey(blank=True, help_text='HT__TO_SUBSCRIPTION', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.subscription', verbose_name='VN__TO_SUBSCRIPTION'),
        ),
    ]
