# Generated by Django 3.1.7 on 2021-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_auto_20210407_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='merchant_id',
            field=models.CharField(default='', help_text='HT__MERCHANT_ID', max_length=128, verbose_name='VN__MERCHANT_ID'),
            preserve_default=False,
        ),
    ]
