# Generated by Django 3.1.7 on 2021-04-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_subscription_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_default',
            field=models.BooleanField(default=False, help_text='HT__IS_DEFAULT', verbose_name='VN__IS_DEFAULT'),
        ),
    ]
