# Generated by Django 3.1.7 on 2021-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_tariff_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='merchant_id',
            field=models.CharField(blank=True, help_text='HT__MERCHANT_ID', max_length=128, null=True, verbose_name='VN__MERCHANT_ID'),
        ),
    ]
