# Generated by Django 2.2.8 on 2019-12-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20191204_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, help_text="HT__EMAIL", max_length=50, verbose_name="VN__EMAIL"),
        ),
    ]
