# Generated by Django 2.2.8 on 2020-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191212_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, help_text='HT__AVATAR', verbose_name='VN__AVATAR'),
        ),
    ]
