# Generated by Django 3.1.7 on 2021-03-02 13:53

import apps.users.models.reset_password_request
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, default=apps.users.models.reset_password_request.default_code, help_text='HT__CODE', max_length=6, verbose_name='VN__CODE')),
                ('expired_at', models.DateTimeField(default=apps.users.models.reset_password_request.default_expired_at, help_text='HT__EXPIRED_AT', verbose_name='VN__EXPIRED_AT')),
                ('user', models.ForeignKey(help_text='HT__USER', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='VN__USER')),
            ],
            options={
                'verbose_name': 'VN__RESET_PASSWORD_REQUEST',
                'verbose_name_plural': 'VN__RESET_PASSWORD_REQUESTS',
                'ordering': ('-created_at',),
            },
        ),
    ]
