# Generated by Django 3.1.7 on 2021-03-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_resetpasswordrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='HT__EMAIL', max_length=128, verbose_name='VN__EMAIL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, help_text='HT__LOGIN', max_length=128, unique=True, verbose_name='VN__LOGIN'),
        ),
    ]
