# Generated by Django 3.1.7 on 2021-03-09 13:53

import apps.users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210305_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='HT__AVATAR', max_length=256, upload_to=apps.users.models.user.avatar_upload_to, verbose_name='VN__AVATAR'),
        ),
    ]
