# Generated by Django 3.1.7 on 2021-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210309_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, help_text='HT__LOGIN', max_length=128, unique=True, verbose_name='VN__LOGIN'),
        ),
    ]
