# Generated by Django 3.1.7 on 2021-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210402_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='HT__LAST_NAME', max_length=50, verbose_name='VN__LAST_NAME'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='HT__FIRST_NAME', max_length=50, verbose_name='VN__FIRST_NAME'),
        ),
    ]
