# Generated by Django 3.1.7 on 2021-04-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210402_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'VN__USER', 'verbose_name_plural': 'VN__USERS'},
        ),
    ]
