# Generated by Django 3.1.7 on 2021-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_fill_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='HT__EMAIL', max_length=254, unique=True, verbose_name='VN__EMAIL'),
        ),
    ]
