# Generated by Django 3.1.10 on 2021-05-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210506_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='old_avatar',
        ),
    ]
