# Generated by Django 3.1.10 on 2021-05-14 08:02

import apps.media.models.fields.image
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20210506_1647'),
        ('users', '0019_auto_20210514_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=apps.media.models.fields.image.ImageField(blank=True, help_text='HT__AVATAR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.image', verbose_name='VN__AVATAR'),
        ),
    ]
