# Generated by Django 3.1.10 on 2021-05-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_avatar',
        ),
    ]
